version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080
      - NASA_API_KEY=1QktG8hbbRmodGBSGhfa8qhE2PNboiL7cbqXrjDK
    restart: unless-stopped

  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api